// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXLWezX4Ly0Ci_kgfXOKt9HA5mw70AlBQ',
    appId: '1:864145991964:web:d725b12e22905a665eb2d9',
    messagingSenderId: '864145991964',
    projectId: 'nomadgo-b32de',
    authDomain: 'nomadgo-b32de.firebaseapp.com',
    storageBucket: 'nomadgo-b32de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCdDF7jQd8EQa4Ew2Q1I04aCs1DarIKME',
    appId: '1:864145991964:android:b653a05d408277d45eb2d9',
    messagingSenderId: '864145991964',
    projectId: 'nomadgo-b32de',
    storageBucket: 'nomadgo-b32de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRo43Sq-oCi2SS-QB4KxATNyenlG5BGDM',
    appId: '1:864145991964:ios:441596408c94cbb25eb2d9',
    messagingSenderId: '864145991964',
    projectId: 'nomadgo-b32de',
    storageBucket: 'nomadgo-b32de.firebasestorage.app',
    iosBundleId: 'com.example.flutterCleanArchitecturePractise',
  );
}
